/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaDiseño;

import CapaNegocio.CCita;
import CapaNegocio.Errores;
import Encapsulamiento.ECita;
import java.awt.Image;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author vladimir
 */
public class Cita extends javax.swing.JPanel {

    public boolean visible = true;
    public boolean noVisible = false;

    /**
     * Creates new form Cita
     */
    public Cita() {
        initComponents();

//        ImageIcon imgIcon = new ImageIcon(getClass().getResource("/Imagen/wallpaper.jpg"));
//        Image imgEscalada = imgIcon.getImage().getScaledInstance(lbImagen.getWidth(),
//                lbImagen.getHeight(), Image.SCALE_SMOOTH);
//        Icon iconoEscalado = new ImageIcon(imgEscalada);
//        lbImagen.setIcon(iconoEscalado);

        String[] Fecha = Cliente.lbFecha.getText().split("-");
        ECita.setFecha(Fecha[2] + "-" + Fecha[1]);
        CCita.Listar_Por_Fecha();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCita = new javax.swing.JPanel();
        panelCalendario = new javax.swing.JPanel();
        calendario = new com.toedter.calendar.JCalendar();
        btnNuevaCita = new javax.swing.JButton();
        btnMensualmente = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelSemanal = new javax.swing.JPanel();
        panelMes1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSemana = new javax.swing.JTable();
        panelMes2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbSemana1 = new javax.swing.JTable();
        panelMes3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbSemana2 = new javax.swing.JTable();
        panelMes4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbSemana3 = new javax.swing.JTable();
        panelMes5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbSemana4 = new javax.swing.JTable();
        panelMes6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbSemana5 = new javax.swing.JTable();
        panelCitasMes = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbListaCitas = new javax.swing.JTable();

        panelCita.setMaximumSize(new java.awt.Dimension(1018, 667));
        panelCita.setMinimumSize(new java.awt.Dimension(1018, 667));
        panelCita.setPreferredSize(new java.awt.Dimension(1018, 667));
        panelCita.setLayout(null);

        panelCalendario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 255, 255), null), null), "Calendario ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(0, 102, 102))); // NOI18N
        panelCalendario.setMaximumSize(new java.awt.Dimension(312, 215));
        panelCalendario.setMinimumSize(new java.awt.Dimension(312, 215));
        panelCalendario.setOpaque(false);

        calendario.setBackground(new java.awt.Color(255, 255, 255));
        calendario.setForeground(new java.awt.Color(0, 0, 102));
        calendario.setDecorationBackgroundColor(new java.awt.Color(255, 255, 255));
        calendario.setDecorationBordersVisible(true);
        calendario.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        calendario.setMaximumSize(new java.awt.Dimension(184, 153));
        calendario.setMinimumSize(new java.awt.Dimension(184, 153));
        calendario.setOpaque(false);
        calendario.setSundayForeground(new java.awt.Color(204, 0, 0));
        calendario.setVerifyInputWhenFocusTarget(false);
        calendario.setWeekOfYearVisible(false);
        calendario.setWeekdayForeground(new java.awt.Color(0, 153, 0));
        calendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendarioMouseClicked(evt);
            }
        });

        btnNuevaCita.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnNuevaCita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/citass.png"))); // NOI18N
        btnNuevaCita.setText("Nueva cita");
        btnNuevaCita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevaCitaMouseClicked(evt);
            }
        });

        btnMensualmente.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnMensualmente.setForeground(new java.awt.Color(153, 0, 0));
        btnMensualmente.setText("Vista Mensual");
        btnMensualmente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMensualmente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMensualmente.setMaximumSize(new java.awt.Dimension(149, 29));
        btnMensualmente.setMinimumSize(new java.awt.Dimension(149, 29));
        btnMensualmente.setPreferredSize(new java.awt.Dimension(149, 29));
        btnMensualmente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMensualmenteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelCalendarioLayout = new javax.swing.GroupLayout(panelCalendario);
        panelCalendario.setLayout(panelCalendarioLayout);
        panelCalendarioLayout.setHorizontalGroup(
            panelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCalendarioLayout.createSequentialGroup()
                .addGroup(panelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCalendarioLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelCalendarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnNuevaCita, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(btnMensualmente, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelCalendarioLayout.setVerticalGroup(
            panelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCalendarioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevaCita)
                    .addComponent(btnMensualmente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panelCita.add(panelCalendario);
        panelCalendario.setBounds(10, 0, 310, 210);

        jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        panelSemanal.setMaximumSize(new java.awt.Dimension(663, 628));
        panelSemanal.setMinimumSize(new java.awt.Dimension(663, 628));
        panelSemanal.setOpaque(false);

        panelMes1.setBackground(new java.awt.Color(204, 255, 204));
        panelMes1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 255, 255), null), null), "LUNES", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 102))); // NOI18N
        panelMes1.setMaximumSize(new java.awt.Dimension(335, 195));
        panelMes1.setMinimumSize(new java.awt.Dimension(335, 195));
        panelMes1.setPreferredSize(new java.awt.Dimension(335, 195));

        tbSemana.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tbSemana.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbSemana.setGridColor(new java.awt.Color(255, 255, 255));
        tbSemana.setInheritsPopupMenu(true);
        tbSemana.setMaximumSize(new java.awt.Dimension(296, 144));
        tbSemana.setMinimumSize(new java.awt.Dimension(296, 144));
        tbSemana.setPreferredSize(new java.awt.Dimension(296, 144));
        tbSemana.setSelectionBackground(new java.awt.Color(0, 102, 102));
        tbSemana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSemanaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSemana);

        javax.swing.GroupLayout panelMes1Layout = new javax.swing.GroupLayout(panelMes1);
        panelMes1.setLayout(panelMes1Layout);
        panelMes1Layout.setHorizontalGroup(
            panelMes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMes1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMes1Layout.setVerticalGroup(
            panelMes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMes1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );

        panelMes2.setBackground(new java.awt.Color(204, 255, 153));
        panelMes2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 255, 255), null), null), "MARTES", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 102))); // NOI18N
        panelMes2.setMaximumSize(new java.awt.Dimension(335, 195));
        panelMes2.setMinimumSize(new java.awt.Dimension(335, 195));
        panelMes2.setPreferredSize(new java.awt.Dimension(335, 195));

        tbSemana1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tbSemana1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbSemana1.setGridColor(new java.awt.Color(255, 255, 255));
        tbSemana1.setInheritsPopupMenu(true);
        tbSemana1.setMaximumSize(new java.awt.Dimension(296, 144));
        tbSemana1.setMinimumSize(new java.awt.Dimension(296, 144));
        tbSemana1.setPreferredSize(new java.awt.Dimension(296, 144));
        tbSemana1.setSelectionBackground(new java.awt.Color(0, 102, 102));
        tbSemana1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSemana1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbSemana1);

        javax.swing.GroupLayout panelMes2Layout = new javax.swing.GroupLayout(panelMes2);
        panelMes2.setLayout(panelMes2Layout);
        panelMes2Layout.setHorizontalGroup(
            panelMes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMes2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMes2Layout.setVerticalGroup(
            panelMes2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMes2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );

        panelMes3.setBackground(new java.awt.Color(204, 255, 204));
        panelMes3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 255, 255), null), null), "MIERCOLES", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 102))); // NOI18N
        panelMes3.setMaximumSize(new java.awt.Dimension(335, 195));
        panelMes3.setMinimumSize(new java.awt.Dimension(335, 195));
        panelMes3.setPreferredSize(new java.awt.Dimension(335, 195));

        tbSemana2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tbSemana2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbSemana2.setGridColor(new java.awt.Color(255, 255, 255));
        tbSemana2.setInheritsPopupMenu(true);
        tbSemana2.setMaximumSize(new java.awt.Dimension(296, 144));
        tbSemana2.setMinimumSize(new java.awt.Dimension(296, 144));
        tbSemana2.setPreferredSize(new java.awt.Dimension(296, 144));
        tbSemana2.setSelectionBackground(new java.awt.Color(0, 102, 102));
        tbSemana2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSemana2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbSemana2);

        javax.swing.GroupLayout panelMes3Layout = new javax.swing.GroupLayout(panelMes3);
        panelMes3.setLayout(panelMes3Layout);
        panelMes3Layout.setHorizontalGroup(
            panelMes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMes3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMes3Layout.setVerticalGroup(
            panelMes3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMes3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(262, 262, 262))
        );

        panelMes4.setBackground(new java.awt.Color(204, 255, 153));
        panelMes4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 255, 255), null), null), "JUEVES", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 102))); // NOI18N
        panelMes4.setMaximumSize(new java.awt.Dimension(335, 195));
        panelMes4.setMinimumSize(new java.awt.Dimension(335, 195));
        panelMes4.setPreferredSize(new java.awt.Dimension(335, 195));

        tbSemana3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tbSemana3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbSemana3.setGridColor(new java.awt.Color(255, 255, 255));
        tbSemana3.setInheritsPopupMenu(true);
        tbSemana3.setMaximumSize(new java.awt.Dimension(296, 144));
        tbSemana3.setMinimumSize(new java.awt.Dimension(296, 144));
        tbSemana3.setPreferredSize(new java.awt.Dimension(296, 144));
        tbSemana3.setSelectionBackground(new java.awt.Color(0, 102, 102));
        tbSemana3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSemana3MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbSemana3);

        javax.swing.GroupLayout panelMes4Layout = new javax.swing.GroupLayout(panelMes4);
        panelMes4.setLayout(panelMes4Layout);
        panelMes4Layout.setHorizontalGroup(
            panelMes4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMes4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMes4Layout.setVerticalGroup(
            panelMes4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMes4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );

        panelMes5.setBackground(new java.awt.Color(204, 255, 204));
        panelMes5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 255, 255), null), null), "VIERNES", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 102))); // NOI18N
        panelMes5.setMaximumSize(new java.awt.Dimension(335, 195));
        panelMes5.setMinimumSize(new java.awt.Dimension(335, 195));
        panelMes5.setPreferredSize(new java.awt.Dimension(335, 195));

        tbSemana4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tbSemana4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbSemana4.setGridColor(new java.awt.Color(255, 255, 255));
        tbSemana4.setInheritsPopupMenu(true);
        tbSemana4.setMaximumSize(new java.awt.Dimension(296, 144));
        tbSemana4.setMinimumSize(new java.awt.Dimension(296, 144));
        tbSemana4.setPreferredSize(new java.awt.Dimension(296, 144));
        tbSemana4.setSelectionBackground(new java.awt.Color(0, 102, 102));
        tbSemana4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSemana4MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbSemana4);

        javax.swing.GroupLayout panelMes5Layout = new javax.swing.GroupLayout(panelMes5);
        panelMes5.setLayout(panelMes5Layout);
        panelMes5Layout.setHorizontalGroup(
            panelMes5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMes5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMes5Layout.setVerticalGroup(
            panelMes5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMes5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );

        panelMes6.setBackground(new java.awt.Color(204, 255, 153));
        panelMes6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(153, 255, 255), null), null), "SABADO", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 102, 102))); // NOI18N
        panelMes6.setMaximumSize(new java.awt.Dimension(335, 195));
        panelMes6.setMinimumSize(new java.awt.Dimension(335, 195));
        panelMes6.setPreferredSize(new java.awt.Dimension(335, 195));

        tbSemana5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tbSemana5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbSemana5.setGridColor(new java.awt.Color(255, 255, 255));
        tbSemana5.setInheritsPopupMenu(true);
        tbSemana5.setMaximumSize(new java.awt.Dimension(296, 144));
        tbSemana5.setMinimumSize(new java.awt.Dimension(296, 144));
        tbSemana5.setPreferredSize(new java.awt.Dimension(296, 144));
        tbSemana5.setSelectionBackground(new java.awt.Color(0, 102, 102));
        tbSemana5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSemana5MouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tbSemana5);

        javax.swing.GroupLayout panelMes6Layout = new javax.swing.GroupLayout(panelMes6);
        panelMes6.setLayout(panelMes6Layout);
        panelMes6Layout.setHorizontalGroup(
            panelMes6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMes6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelMes6Layout.setVerticalGroup(
            panelMes6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMes6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(262, 262, 262))
        );

        javax.swing.GroupLayout panelSemanalLayout = new javax.swing.GroupLayout(panelSemanal);
        panelSemanal.setLayout(panelSemanalLayout);
        panelSemanalLayout.setHorizontalGroup(
            panelSemanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSemanalLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panelSemanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMes3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMes5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSemanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMes4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMes6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMes2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelSemanalLayout.setVerticalGroup(
            panelSemanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSemanalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSemanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panelSemanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelSemanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMes6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMes5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Citas semanales", panelSemanal);

        panelCita.add(jTabbedPane1);
        jTabbedPane1.setBounds(327, 0, 690, 656);

        panelCitasMes.setBackground(new java.awt.Color(204, 255, 153));
        panelCitasMes.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null), null), "Citas del Mes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(0, 102, 102))); // NOI18N
        panelCitasMes.setPreferredSize(new java.awt.Dimension(312, 435));

        tbListaCitas.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tbListaCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbListaCitas.setGridColor(new java.awt.Color(255, 255, 255));
        tbListaCitas.setOpaque(false);
        tbListaCitas.setSelectionBackground(new java.awt.Color(0, 102, 102));
        tbListaCitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaCitasMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tbListaCitas);

        javax.swing.GroupLayout panelCitasMesLayout = new javax.swing.GroupLayout(panelCitasMes);
        panelCitasMes.setLayout(panelCitasMesLayout);
        panelCitasMesLayout.setHorizontalGroup(
            panelCitasMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCitasMesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelCitasMesLayout.setVerticalGroup(
            panelCitasMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCitasMesLayout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelCita.add(panelCitasMes);
        panelCitasMes.setBounds(10, 220, 312, 433);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaCitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevaCitaMouseClicked
        NuevaCita nc = new NuevaCita();
        nc.btnModificar.setVisible(noVisible);
        nc.btnEliminar.setVisible(noVisible);
        nc.setVisible(true);
    }//GEN-LAST:event_btnNuevaCitaMouseClicked

    private void tbListaCitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaCitasMouseClicked
        int row = tbListaCitas.getSelectedRow();
        ECita.setIdCliente(Integer.parseInt(tbListaCitas.getValueAt(row, 3).toString()));
        ECita.setIdCita(Integer.parseInt(tbListaCitas.getValueAt(row, 4).toString()));
        NuevaCitaMostrar();
    }//GEN-LAST:event_tbListaCitasMouseClicked

    private void tbSemanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSemanaMouseClicked
        int row = tbSemana.getSelectedRow();
        ECita.setIdCliente(Integer.parseInt(tbSemana.getValueAt(row, 3).toString()));
        ECita.setIdCita(Integer.parseInt(tbSemana.getValueAt(row, 4).toString()));
        NuevaCitaMostrar();
    }//GEN-LAST:event_tbSemanaMouseClicked

    private void tbSemana1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSemana1MouseClicked
        int row = tbSemana1.getSelectedRow();
        ECita.setIdCliente(Integer.parseInt(tbSemana1.getValueAt(row, 3).toString()));
        ECita.setIdCita(Integer.parseInt(tbSemana1.getValueAt(row, 4).toString()));
        NuevaCitaMostrar();
    }//GEN-LAST:event_tbSemana1MouseClicked

    private void tbSemana2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSemana2MouseClicked
        int row = tbSemana2.getSelectedRow();
        ECita.setIdCliente(Integer.parseInt(tbSemana2.getValueAt(row, 3).toString()));
        ECita.setIdCita(Integer.parseInt(tbSemana2.getValueAt(row, 4).toString()));
        NuevaCitaMostrar();
    }//GEN-LAST:event_tbSemana2MouseClicked

    private void tbSemana3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSemana3MouseClicked
        int row = tbSemana3.getSelectedRow();
        ECita.setIdCliente(Integer.parseInt(tbSemana3.getValueAt(row, 3).toString()));
        ECita.setIdCita(Integer.parseInt(tbSemana3.getValueAt(row, 4).toString()));
        NuevaCitaMostrar();
    }//GEN-LAST:event_tbSemana3MouseClicked

    private void tbSemana4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSemana4MouseClicked
        int row = tbSemana4.getSelectedRow();
        ECita.setIdCliente(Integer.parseInt(tbSemana4.getValueAt(row, 3).toString()));
        ECita.setIdCita(Integer.parseInt(tbSemana4.getValueAt(row, 4).toString()));
        NuevaCitaMostrar();
    }//GEN-LAST:event_tbSemana4MouseClicked

    private void tbSemana5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSemana5MouseClicked
        int row = tbSemana5.getSelectedRow();
        ECita.setIdCliente(Integer.parseInt(tbSemana5.getValueAt(row, 3).toString()));
        ECita.setIdCita(Integer.parseInt(tbSemana5.getValueAt(row, 4).toString()));
        NuevaCitaMostrar();
    }//GEN-LAST:event_tbSemana5MouseClicked

    private void calendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarioMouseClicked

        String dia = String.valueOf(calendario.getCalendar().get(Calendar.DAY_OF_MONTH));
        if (Integer.parseInt(dia) > 9) {
            dia = dia;
        } else {
            dia = "0" + dia;
        }
        String mes = String.valueOf((calendario.getCalendar().get(Calendar.MONTH) + 1));
        if (Integer.parseInt(mes) > 9) {
            mes = mes;
        } else {
            mes = "0" + mes;
        }
        String año = String.valueOf(calendario.getCalendar().get(Calendar.YEAR));
        if (btnMensualmente.getText().equals("Vista Mensual")) {
            ECita.setFecha(año + "-" + mes);
            CCita.Listar_Por_Fecha();
        } else {
            ECita.setFecha(año + "-" + mes + "-" + dia);
            CCita.Listar_Por_Fecha();
        }
    }//GEN-LAST:event_calendarioMouseClicked

    private void btnMensualmenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMensualmenteMouseClicked
        if (btnMensualmente.getText().equals("Vista Mensual")) {
            btnMensualmente.setText("Vista Diaria");
        } else {
            btnMensualmente.setText("Vista Mensual");
        }
    }//GEN-LAST:event_btnMensualmenteMouseClicked
    public void NuevaCitaMostrar() {
        try {
            String Fecha = "";
            String[] Hora;
            SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
            NuevaCita nc = new NuevaCita();
            nc.btnBuscar.setVisible(noVisible);
            nc.btnGuardar.setVisible(noVisible);
            nc.rbCR.setEnabled(noVisible);
            nc.rbNC.setEnabled(noVisible);
            nc.txtAP.setEnabled(noVisible);
            nc.txtAM.setEnabled(noVisible);
            nc.txtN.setEnabled(noVisible);
            nc.txtDNI.setEnabled(noVisible);
            nc.txtT.setEnabled(noVisible);
            ResultSet rs = CCita.BuscarId();
            while (rs.next()) {
                nc.txtAP.setText(rs.getString(1));
                nc.txtAM.setText(rs.getString(2));
                nc.txtN.setText(rs.getString(3));
                nc.txtDNI.setText(rs.getString(4));
                nc.txtT.setText(rs.getString(5));
                Hora = rs.getString(6).split(" ");
                nc.txtHoraReserva.setText(Hora[0]);
                nc.cbHorario.setSelectedItem(Hora[1]);
                Date dateValue;
                try {
                    Fecha = rs.getDate(7).toString();
                    if (Fecha.equals("")) {
                        dateValue = date.parse(Errores.FormatoFecha("0001-01-01"));
                    } else {
                        dateValue = date.parse(Errores.FormatoFecha(Fecha));
                    }
                    nc.txtFecha.setDate(dateValue);
                } catch (Exception ex) {
                    Logger.getLogger(Cliente.class.getName()).log(Level.SEVERE, null, ex);
                }
                nc.txtMotivoConsulta.setText(rs.getString(8));
            }
            nc.setLocationRelativeTo(null);
            nc.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Cita.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMensualmente;
    public static javax.swing.JButton btnNuevaCita;
    public static com.toedter.calendar.JCalendar calendario;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelCalendario;
    public static javax.swing.JPanel panelCita;
    public static javax.swing.JPanel panelCitasMes;
    public static javax.swing.JPanel panelMes1;
    public static javax.swing.JPanel panelMes2;
    public static javax.swing.JPanel panelMes3;
    public static javax.swing.JPanel panelMes4;
    public static javax.swing.JPanel panelMes5;
    public static javax.swing.JPanel panelMes6;
    public static javax.swing.JPanel panelSemanal;
    public static javax.swing.JTable tbListaCitas;
    public static javax.swing.JTable tbSemana;
    public static javax.swing.JTable tbSemana1;
    public static javax.swing.JTable tbSemana2;
    public static javax.swing.JTable tbSemana3;
    public static javax.swing.JTable tbSemana4;
    public static javax.swing.JTable tbSemana5;
    // End of variables declaration//GEN-END:variables
}
