package CapaDiseño;

import CapaNegocio.CConsulta;
import CapaNegocio.Errores;
import CapaNegocio.PintarCeldas;
import Encapsulamiento.ECliente;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author vladimir
 */
public class Consulta extends javax.swing.JPanel implements Printable {

    /**
     * Creates new form fromImpresion1
     */
    public Consulta() {
        initComponents();
        Inicio();
        tbConsulta.setDefaultRenderer(Object.class, new PintarCeldas());
        txtTotal.setText("0.0");
        txtDNI.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();

                // Verificar si la tecla pulsada no es un digito
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
                    e.consume();  // ignorar el evento de teclado
                }
            }
        });
        txtFecha.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();

                // Verificar si la tecla pulsada no es un digito
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
                    if (caracter != '-') {
                        e.consume();  // ignorar el evento de teclado
                    }

                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelImpresion = new javax.swing.JPanel();
        paBoleta = new javax.swing.JPanel();
        paCabecera = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JLabel();
        txtRegion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtCop = new javax.swing.JLabel();
        txtCelularClaro = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtCelularMovistar = new javax.swing.JLabel();
        paCuerpo = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbConsulta = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtApellidoPaterno = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        paPie4 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnImprimir = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtBuscarNombre = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        jLabel7.setText("jLabel7");

        jButton1.setText("jButton1");

        panelImpresion.setBackground(java.awt.SystemColor.textHighlightText);
        panelImpresion.setAutoscrolls(true);
        panelImpresion.setMinimumSize(new java.awt.Dimension(800, 530));
        panelImpresion.setPreferredSize(new java.awt.Dimension(1000, 530));

        paBoleta.setBackground(new java.awt.Color(255, 255, 255));
        paBoleta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        paBoleta.setAutoscrolls(true);
        paBoleta.setMinimumSize(new java.awt.Dimension(815, 460));
        paBoleta.setRequestFocusEnabled(false);
        paBoleta.setVerifyInputWhenFocusTarget(false);

        paCabecera.setBackground(new java.awt.Color(255, 255, 255));
        paCabecera.setAutoscrolls(true);
        paCabecera.setMinimumSize(new java.awt.Dimension(815, 460));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/TituloZamy.png"))); // NOI18N
        imgLogo.setAutoscrolls(true);
        imgLogo.setMinimumSize(new java.awt.Dimension(103, 20));

        txtNombreCompleto.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtNombreCompleto.setAutoscrolls(true);
        txtNombreCompleto.setMinimumSize(new java.awt.Dimension(103, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel3.setText("COP: ");
        jLabel3.setAutoscrolls(true);
        jLabel3.setMinimumSize(new java.awt.Dimension(103, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel4.setText("CIRUJANO DENTISTA");
        jLabel4.setAutoscrolls(true);
        jLabel4.setMinimumSize(new java.awt.Dimension(103, 20));

        txtDireccion.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtDireccion.setText("                                                                                                    ");
        txtDireccion.setAutoscrolls(true);
        txtDireccion.setMinimumSize(new java.awt.Dimension(103, 20));

        txtRegion.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtRegion.setText("                                                            ");
        txtRegion.setAutoscrolls(true);
        txtRegion.setMinimumSize(new java.awt.Dimension(103, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel2.setText("Claro: ");
        jLabel2.setAutoscrolls(true);
        jLabel2.setMinimumSize(new java.awt.Dimension(103, 20));

        jLabel22.setBackground(new java.awt.Color(0, 0, 102));
        jLabel22.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("ODONTOLOGIA GENERAL                                ORTODONCIA                                PEDIATRIA                                REHABLITACION INTEGRAL");
        jLabel22.setToolTipText("");
        jLabel22.setAutoscrolls(true);
        jLabel22.setMinimumSize(new java.awt.Dimension(103, 20));
        jLabel22.setOpaque(true);

        txtCop.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtCop.setText("          ");

        txtCelularClaro.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtCelularClaro.setText("                                           ");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel16.setText("Movistar: ");
        jLabel16.setAutoscrolls(true);
        jLabel16.setMinimumSize(new java.awt.Dimension(103, 20));

        txtCelularMovistar.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtCelularMovistar.setText("                                       ");

        javax.swing.GroupLayout paCabeceraLayout = new javax.swing.GroupLayout(paCabecera);
        paCabecera.setLayout(paCabeceraLayout);
        paCabeceraLayout.setHorizontalGroup(
            paCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paCabeceraLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCop))
                    .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(177, 177, 177)
                .addGroup(paCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paCabeceraLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCelularClaro, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCelularMovistar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        paCabeceraLayout.setVerticalGroup(
            paCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paCabeceraLayout.createSequentialGroup()
                        .addGroup(paCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCelularMovistar))
                            .addGroup(paCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCelularClaro))
                            .addGroup(paCabeceraLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCop))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        paCuerpo.setBackground(new java.awt.Color(255, 255, 255));
        paCuerpo.setAutoscrolls(true);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setText("Nombre:");
        jLabel8.setAutoscrolls(true);

        txtNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNombre.setName("aa"); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel10.setText("DNI:");
        jLabel10.setAutoscrolls(true);

        txtDNI.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel23.setText("Fecha:");
        jLabel23.setAutoscrolls(true);

        txtFecha.setAutoscrolls(true);
        txtFecha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jScrollPane2.setAutoscrolls(true);

        tbConsulta.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tbConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NRO PIEZAS", "DESCRIPCION", "PRECIO"
            }
        ));
        tbConsulta.setGridColor(new java.awt.Color(255, 255, 255));
        tbConsulta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tbConsultaFocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(tbConsulta);
        if (tbConsulta.getColumnModel().getColumnCount() > 0) {
            tbConsulta.getColumnModel().getColumn(0).setMinWidth(80);
            tbConsulta.getColumnModel().getColumn(0).setPreferredWidth(80);
            tbConsulta.getColumnModel().getColumn(0).setMaxWidth(80);
            tbConsulta.getColumnModel().getColumn(1).setMinWidth(500);
            tbConsulta.getColumnModel().getColumn(1).setPreferredWidth(500);
            tbConsulta.getColumnModel().getColumn(1).setMaxWidth(500);
            tbConsulta.getColumnModel().getColumn(2).setMinWidth(100);
            tbConsulta.getColumnModel().getColumn(2).setPreferredWidth(100);
            tbConsulta.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/LogoZamy.png"))); // NOI18N
        jLabel13.setAutoscrolls(true);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel12.setText("TOTAL     S/.");
        jLabel12.setAutoscrolls(true);

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(204, 0, 0));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel11.setText("Apellido Paterno:");
        jLabel11.setAutoscrolls(true);

        txtApellidoPaterno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtApellidoPaterno.setName("aa"); // NOI18N

        txtApellidoMaterno.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtApellidoMaterno.setName("aa"); // NOI18N

        jLabel15.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel15.setText("Apellido Materno:");
        jLabel15.setAutoscrolls(true);

        javax.swing.GroupLayout paCuerpoLayout = new javax.swing.GroupLayout(paCuerpo);
        paCuerpo.setLayout(paCuerpoLayout);
        paCuerpoLayout.setHorizontalGroup(
            paCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paCuerpoLayout.createSequentialGroup()
                .addGroup(paCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(paCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paCuerpoLayout.createSequentialGroup()
                        .addComponent(txtNombre)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(paCuerpoLayout.createSequentialGroup()
                        .addGroup(paCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paCuerpoLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(paCuerpoLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))))
        );
        paCuerpoLayout.setVerticalGroup(
            paCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paCuerpoLayout.createSequentialGroup()
                .addGroup(paCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(paCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paCuerpoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(paCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paCuerpoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)))
                .addGroup(paCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paCuerpoLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        paPie4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel44.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel44.setText("Consultenos tambien a nuestro correo :");

        txtCorreo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jLabel47.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Facebook_Zamy.png"))); // NOI18N

        jLabel14.setBackground(new java.awt.Color(0, 0, 102));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("ODONTOLOGIA GENERAL                                ORTODONCIA                                PEDIATRIA                                REHABLITACION INTEGRAL");
        jLabel14.setToolTipText("");
        jLabel14.setAutoscrolls(true);
        jLabel14.setOpaque(true);

        javax.swing.GroupLayout paPie4Layout = new javax.swing.GroupLayout(paPie4);
        paPie4.setLayout(paPie4Layout);
        paPie4Layout.setHorizontalGroup(
            paPie4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paPie4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel47)
                .addGap(69, 69, 69))
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        paPie4Layout.setVerticalGroup(
            paPie4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paPie4Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paPie4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paPie4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(paPie4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel44)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout paBoletaLayout = new javax.swing.GroupLayout(paBoleta);
        paBoleta.setLayout(paBoletaLayout);
        paBoletaLayout.setHorizontalGroup(
            paBoletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paCabecera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(paPie4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paBoletaLayout.createSequentialGroup()
                .addComponent(paCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        paBoletaLayout.setVerticalGroup(
            paBoletaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paBoletaLayout.createSequentialGroup()
                .addComponent(paCabecera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paPie4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setAutoscrolls(true);

        btnImprimir.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel9.setText("Nombre:");

        txtBuscarNombre.setBackground(new java.awt.Color(255, 255, 153));
        txtBuscarNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true));

        btnBuscar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnImprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 585, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar)
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnImprimir)
                .addComponent(jLabel9)
                .addComponent(txtBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnBuscar))
        );

        javax.swing.GroupLayout panelImpresionLayout = new javax.swing.GroupLayout(panelImpresion);
        panelImpresion.setLayout(panelImpresionLayout);
        panelImpresionLayout.setHorizontalGroup(
            panelImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paBoleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelImpresionLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        panelImpresionLayout.setVerticalGroup(
            panelImpresionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImpresionLayout.createSequentialGroup()
                .addComponent(paBoleta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImpresion, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImpresion, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        try {
            PrinterJob trab = PrinterJob.getPrinterJob();
            trab.setPrintable(this);
            boolean impr = trab.printDialog();

            if (impr) {
                trab.print();
            }
        } catch (PrinterException pex) {
            Errores.Error("Error\n" + pex);
        }
        Limpiar();
    }//GEN-LAST:event_btnImprimirActionPerformed
    public void Limpiar() {
        txtApellidoMaterno.setText("");
        txtApellidoPaterno.setText("");
        txtDNI.setText("");
        txtFecha.setCalendar(null);
        txtNombre.setText("");
        txtTotal.setText("0");
        tbConsulta.removeAll();
        tbConsulta.repaint();
    }
    private void tbConsultaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tbConsultaFocusGained
        double Total = 0;
        String pieza = "";
        String costo = "";
        int Columnas = tbConsulta.getRowCount();
        for (int i = 0; i < Columnas; i++) {
            if (tbConsulta.getValueAt(i, 2) == null) {
                break;
            } else {
                if (tbConsulta.getValueAt(i, 0) == null) {
                    pieza = "0";
                } else {
                    pieza = tbConsulta.getValueAt(i, 0).toString();
                }
                if (tbConsulta.getValueAt(i, 2) == null) {
                    costo = "0";
                } else {
                    costo = tbConsulta.getValueAt(i, 2).toString();
                }
                Total = Total + Double.parseDouble(pieza) * Double.parseDouble(costo);

                txtTotal.setText(String.valueOf(Total));
            }
        }
    }//GEN-LAST:event_tbConsultaFocusGained

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        ECliente.setNombre(txtBuscarNombre.getText());
        ConsultaCliente c = new ConsultaCliente();
        c.setLocationRelativeTo(null);
        CConsulta.Listar();
        c.setVisible(true);
    }//GEN-LAST:event_btnBuscarMouseClicked

    public void Inicio() {
        ResultSet rs = CConsulta.RecuperarInformacion();
        if (rs == null) {
            Errores.Error("No se puede recuperar informacion personal en consulta");
        } else {
            try {
                while (rs.next()) {
                    txtNombreCompleto.setText(rs.getString(1));
                    txtCop.setText(rs.getString(2));
                    txtCelularClaro.setText(rs.getString(3));
                    txtCelularMovistar.setText(rs.getString(4));
                    txtDireccion.setText(rs.getString(5));
                    txtRegion.setText(rs.getString(6));
                    txtCorreo.setText(rs.getString(7));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Consulta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JPanel paBoleta;
    private javax.swing.JPanel paCabecera;
    public static javax.swing.JPanel paCuerpo;
    private javax.swing.JPanel paPie4;
    public static javax.swing.JPanel panelImpresion;
    public static javax.swing.JTable tbConsulta;
    public static javax.swing.JTextField txtApellidoMaterno;
    public static javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtBuscarNombre;
    public static javax.swing.JLabel txtCelularClaro;
    public static javax.swing.JLabel txtCelularMovistar;
    public static javax.swing.JLabel txtCop;
    public static javax.swing.JLabel txtCorreo;
    public static javax.swing.JTextField txtDNI;
    public static javax.swing.JLabel txtDireccion;
    private com.toedter.calendar.JDateChooser txtFecha;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JLabel txtNombreCompleto;
    public static javax.swing.JLabel txtRegion;
    public static javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graf, PageFormat pagfor, int page) throws PrinterException {
        if (page > 0) {
            return NO_SUCH_PAGE;
        }
        Graphics2D bot = (Graphics2D) graf;
        bot.translate(pagfor.getImageableX() + 50, pagfor.getImageableY() + 50);
        bot.scale(0.5, 0.5);
        paBoleta.printAll(graf);
        return PAGE_EXISTS;
    }
}
