/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaDiseño;

/**
 *
 * @author vladimir
 */
public class Economia extends javax.swing.JPanel {

    /**
     * Creates new form Economia
     */
    public Economia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbEconomia = new javax.swing.JTabbedPane();
        ingreso1 = new CapaDiseño.Ingreso();
        egresos1 = new CapaDiseño.Egresos();
        egresosvsIngresos2 = new CapaDiseño.EgresosvsIngresos();

        tbEconomia.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        tbEconomia.addTab("Ingresos", ingreso1);
        tbEconomia.addTab("Egresos", egresos1);
        tbEconomia.addTab("Ingresos vs Egresos", egresosvsIngresos2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbEconomia)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbEconomia)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CapaDiseño.Egresos egresos1;
    private CapaDiseño.EgresosvsIngresos egresosvsIngresos2;
    private CapaDiseño.Ingreso ingreso1;
    public static javax.swing.JTabbedPane tbEconomia;
    // End of variables declaration//GEN-END:variables
}
