/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaDiseño;

import CapaNegocio.CEgreso;
import CapaNegocio.CGraficarEgresos;
import CapaNegocio.Errores;
import Encapsulamiento.EEgresos;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author vladimir
 */
public class Egresos extends javax.swing.JPanel {

    boolean v = true;
    boolean nv = false;

    /**
     * Creates new form Egresos
     */
    public Egresos() {
        initComponents();
        Iniciar();
    }

    public static void Iniciar() {
        String[] Fecha = Cliente.lbFecha.getText().split("-");
        EEgresos.setFecha(Fecha[2] + "-" + Fecha[1]);
        txtEgresoMensual.setText(String.valueOf(CEgreso.Listar_Egresos_Proveedor()));
        CGraficarEgresos g = new CGraficarEgresos();
        panelGrafico.add(g.graficar());
    }

    public static void Actualizar() {
        String[] Fecha = Cliente.lbFecha.getText().split("-");
        EEgresos.setFecha(Fecha[2] + "-" + Fecha[1]);
        txtEgresoMensual.setText(String.valueOf(CEgreso.Listar_Egresos_Proveedor()));
        CGraficarEgresos g = new CGraficarEgresos();
        panelGrafico.removeAll();
        panelGrafico.add(g.graficar());
        panelGrafico.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelProveedor = new javax.swing.JPanel();
        panelFecha = new javax.swing.JPanel();
        calendario = new com.toedter.calendar.JCalendar();
        panelFuncionEgresos = new javax.swing.JPanel();
        btnNuevoEgreso = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnMensualmente = new javax.swing.JButton();
        tpListaEgresos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEgresos = new javax.swing.JTable();
        panelGrafico = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtEgresoMensual = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1018, 640));
        setMinimumSize(new java.awt.Dimension(1018, 640));
        setPreferredSize(new java.awt.Dimension(1018, 640));

        panelProveedor.setMaximumSize(new java.awt.Dimension(1018, 650));
        panelProveedor.setMinimumSize(new java.awt.Dimension(1018, 650));
        panelProveedor.setLayout(null);

        panelFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null), null), "Busqueda egreso", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(0, 102, 102))); // NOI18N
        panelFecha.setOpaque(false);

        calendario.setBackground(new java.awt.Color(255, 255, 255));
        calendario.setForeground(new java.awt.Color(0, 0, 102));
        calendario.setDecorationBackgroundColor(new java.awt.Color(255, 255, 255));
        calendario.setDecorationBordersVisible(true);
        calendario.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        calendario.setMaximumSize(new java.awt.Dimension(184, 153));
        calendario.setMinimumSize(new java.awt.Dimension(184, 153));
        calendario.setSundayForeground(new java.awt.Color(204, 0, 0));
        calendario.setVerifyInputWhenFocusTarget(false);
        calendario.setWeekOfYearVisible(false);
        calendario.setWeekdayForeground(new java.awt.Color(0, 153, 0));
        calendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelFechaLayout = new javax.swing.GroupLayout(panelFecha);
        panelFecha.setLayout(panelFechaLayout);
        panelFechaLayout.setHorizontalGroup(
            panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFechaLayout.setVerticalGroup(
            panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panelProveedor.add(panelFecha);
        panelFecha.setBounds(10, 0, 240, 184);

        panelFuncionEgresos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null), null), "Nuevo Egreso", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(0, 102, 102))); // NOI18N
        panelFuncionEgresos.setOpaque(false);

        btnNuevoEgreso.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnNuevoEgreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/egresoss.png"))); // NOI18N
        btnNuevoEgreso.setText("Nuevo egreso");
        btnNuevoEgreso.setMaximumSize(new java.awt.Dimension(149, 29));
        btnNuevoEgreso.setMinimumSize(new java.awt.Dimension(149, 29));
        btnNuevoEgreso.setPreferredSize(new java.awt.Dimension(149, 29));
        btnNuevoEgreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoEgresoMouseClicked(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/EliminarEgresos.png"))); // NOI18N
        btnEliminar.setText("Eliminar egreso");
        btnEliminar.setMaximumSize(new java.awt.Dimension(149, 29));
        btnEliminar.setMinimumSize(new java.awt.Dimension(149, 29));
        btnEliminar.setPreferredSize(new java.awt.Dimension(149, 29));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        btnMensualmente.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnMensualmente.setForeground(new java.awt.Color(153, 0, 0));
        btnMensualmente.setText("Vista Mensual");
        btnMensualmente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMensualmente.setMaximumSize(new java.awt.Dimension(149, 29));
        btnMensualmente.setMinimumSize(new java.awt.Dimension(149, 29));
        btnMensualmente.setPreferredSize(new java.awt.Dimension(149, 29));
        btnMensualmente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMensualmenteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelFuncionEgresosLayout = new javax.swing.GroupLayout(panelFuncionEgresos);
        panelFuncionEgresos.setLayout(panelFuncionEgresosLayout);
        panelFuncionEgresosLayout.setHorizontalGroup(
            panelFuncionEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFuncionEgresosLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelFuncionEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNuevoEgreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMensualmente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelFuncionEgresosLayout.setVerticalGroup(
            panelFuncionEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFuncionEgresosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNuevoEgreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMensualmente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelProveedor.add(panelFuncionEgresos);
        panelFuncionEgresos.setBounds(10, 202, 240, 170);

        tpListaEgresos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null), null)));
        tpListaEgresos.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        jPanel1.setOpaque(false);

        tbEgresos.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tbEgresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbEgresos.setGridColor(new java.awt.Color(255, 255, 255));
        tbEgresos.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(tbEgresos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpListaEgresos.addTab("Mis egresos", jPanel1);

        panelGrafico.setOpaque(false);

        javax.swing.GroupLayout panelGraficoLayout = new javax.swing.GroupLayout(panelGrafico);
        panelGrafico.setLayout(panelGraficoLayout);
        panelGraficoLayout.setHorizontalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 743, Short.MAX_VALUE)
        );
        panelGraficoLayout.setVerticalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        tpListaEgresos.addTab("Grafico de mis egresos", panelGrafico);

        panelProveedor.add(tpListaEgresos);
        tpListaEgresos.setBounds(260, 0, 752, 630);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null), null), "Egreso Total ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(256, 72));
        jPanel2.setMinimumSize(new java.awt.Dimension(256, 72));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(256, 72));

        txtEgresoMensual.setEditable(false);
        txtEgresoMensual.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtEgresoMensual.setForeground(new java.awt.Color(153, 0, 0));
        txtEgresoMensual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("S./");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEgresoMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEgresoMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );

        panelProveedor.add(jPanel2);
        jPanel2.setBounds(10, 560, 240, 72);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 1018, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 640, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoEgresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoEgresoMouseClicked
        NuevoEgreso ne = new NuevoEgreso();
        ne.rbRegistrado.setSelected(false);
        ne.setLocationRelativeTo(null);
        ne.setVisible(v);
    }//GEN-LAST:event_btnNuevoEgresoMouseClicked

    private void calendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarioMouseClicked
        String dia = String.valueOf(calendario.getCalendar().get(Calendar.DAY_OF_MONTH));
        if (Integer.parseInt(dia) > 9) {
            dia = dia;
        } else {
            dia = "0" + dia;
        }
        String mes = String.valueOf((calendario.getCalendar().get(Calendar.MONTH) + 1));
        if (Integer.parseInt(mes) > 9) {
            mes = mes;
        } else {
            mes = "0" + mes;
        }
        if (btnMensualmente.getText().equals("Vista Mensual")) {

            String año = String.valueOf(calendario.getCalendar().get(Calendar.YEAR));
            EEgresos.setFecha(año + "-" + mes);
            txtEgresoMensual.setText(String.valueOf(CEgreso.Listar_Egresos_Proveedor()));
            CGraficarEgresos g = new CGraficarEgresos();
            panelGrafico.removeAll();
            panelGrafico.add(g.graficar());
            panelGrafico.repaint();
        } else {
            String año = String.valueOf(calendario.getCalendar().get(Calendar.YEAR));
            EEgresos.setFecha(año + "-" + mes + "-" + dia);
            txtEgresoMensual.setText(String.valueOf(CEgreso.Listar_Egresos_Proveedor()));
            CGraficarEgresos g = new CGraficarEgresos();
            panelGrafico.removeAll();
            panelGrafico.add(g.graficar());
            panelGrafico.repaint();
        }

    }//GEN-LAST:event_calendarioMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        int seleccion1 = JOptionPane.showOptionDialog(null, "¿seguro decea eliminar?"/*componente padre*/, //Mensaje
                "Seleccione una opción", // Título
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, // null para icono por defecto.
                new Object[]{"Si", "No"}, // null para YES, NO y CANCEL
                "Si");
        if (seleccion1 != -1) {
            if ((seleccion1 + 1) == 1) {
                int row = tbEgresos.getSelectedRow();
                if (row > 0) {
                    EEgresos.setIdEgreso(Integer.parseInt(tbEgresos.getValueAt(row, 10).toString()));
                    if (CEgreso.Eliminar()) {
                        String[] Fecha = Cliente.lbFecha.getText().split("-");
                        EEgresos.setFecha(Fecha[2] + "-" + Fecha[1]);
                        txtEgresoMensual.setText(String.valueOf(CEgreso.Listar_Egresos_Proveedor()));
                        Actualizar();
                        Errores.Exito("Egreso eliminado");
                    } else {
                        Errores.Error("Seleccione una fila");
                    }
                } else {
                    Errores.Error("Ocurrio un error");
                }
            }
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnMensualmenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMensualmenteMouseClicked
        if (btnMensualmente.getText().equals("Vista Mensual")) {
            btnMensualmente.setText("Vista Diaria");
        } else {
            btnMensualmente.setText("Vista Mensual");
        }

    }//GEN-LAST:event_btnMensualmenteMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMensualmente;
    public static javax.swing.JButton btnNuevoEgreso;
    public static com.toedter.calendar.JCalendar calendario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JPanel panelFecha;
    public static javax.swing.JPanel panelFuncionEgresos;
    public static javax.swing.JPanel panelGrafico;
    public static javax.swing.JPanel panelProveedor;
    public static javax.swing.JTable tbEgresos;
    public static javax.swing.JTabbedPane tpListaEgresos;
    public static javax.swing.JTextField txtEgresoMensual;
    // End of variables declaration//GEN-END:variables
}
