/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaDiseño;

import CapaNegocio.CGraficarIngresos;
import CapaNegocio.CIngresos;
import Encapsulamiento.EIngresos;
import java.util.Calendar;

/**
 *
 * @author vladimir
 */
public class Ingreso extends javax.swing.JPanel {

    /**
     * Creates new form Ingresos
     */
    public Ingreso() {
        initComponents();
        Iniciar();
    }

    public static void Iniciar() {

        String[] Fecha = Cliente.lbFecha.getText().split("-");
        EIngresos.setFecha(Fecha[2] + "-" + Fecha[1]);
        txtIngresoMensual.setText(String.valueOf(CIngresos.Listar_Ingresos()));
        
        panelGrafico.add(CGraficarIngresos.graficar());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIngresos = new javax.swing.JPanel();
        panelFecha = new javax.swing.JPanel();
        calendario = new com.toedter.calendar.JCalendar();
        btnMensualmente = new javax.swing.JButton();
        tpListaIngresos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbIngresos = new javax.swing.JTable();
        panelGrafico = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIngresoMensual = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(1018, 640));
        setMinimumSize(new java.awt.Dimension(1018, 640));
        setPreferredSize(new java.awt.Dimension(1018, 640));

        panelIngresos.setLayout(null);

        panelFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null), null), "Busqueda ingreso", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(0, 102, 102))); // NOI18N
        panelFecha.setOpaque(false);

        calendario.setBackground(new java.awt.Color(255, 255, 255));
        calendario.setForeground(new java.awt.Color(0, 0, 102));
        calendario.setDecorationBackgroundColor(new java.awt.Color(255, 255, 255));
        calendario.setDecorationBordersVisible(true);
        calendario.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        calendario.setMaximumSize(new java.awt.Dimension(184, 153));
        calendario.setMinimumSize(new java.awt.Dimension(184, 153));
        calendario.setSundayForeground(new java.awt.Color(204, 0, 0));
        calendario.setVerifyInputWhenFocusTarget(false);
        calendario.setWeekOfYearVisible(false);
        calendario.setWeekdayForeground(new java.awt.Color(0, 153, 0));
        calendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendarioMouseClicked(evt);
            }
        });

        btnMensualmente.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnMensualmente.setForeground(new java.awt.Color(153, 0, 0));
        btnMensualmente.setText("Vista Mensual");
        btnMensualmente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMensualmente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMensualmenteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelFechaLayout = new javax.swing.GroupLayout(panelFecha);
        panelFecha.setLayout(panelFechaLayout);
        panelFechaLayout.setHorizontalGroup(
            panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFechaLayout.createSequentialGroup()
                .addGroup(panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFechaLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(btnMensualmente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFechaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFechaLayout.setVerticalGroup(
            panelFechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFechaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnMensualmente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelIngresos.add(panelFecha);
        panelFecha.setBounds(8, 0, 252, 270);

        tpListaIngresos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 255, 255), null), null)));
        tpListaIngresos.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N

        jPanel1.setOpaque(false);

        tbIngresos.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tbIngresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbIngresos.setGridColor(new java.awt.Color(255, 255, 255));
        tbIngresos.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(tbIngresos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
        );

        tpListaIngresos.addTab("Mis ingresos", jPanel1);

        panelGrafico.setOpaque(false);

        javax.swing.GroupLayout panelGraficoLayout = new javax.swing.GroupLayout(panelGrafico);
        panelGrafico.setLayout(panelGraficoLayout);
        panelGraficoLayout.setHorizontalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
        );
        panelGraficoLayout.setVerticalGroup(
            panelGraficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        tpListaIngresos.addTab("Grafico de mis ingresos", panelGrafico);

        panelIngresos.add(tpListaIngresos);
        tpListaIngresos.setBounds(274, 0, 745, 630);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingreso Total", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 11), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel2.setMaximumSize(new java.awt.Dimension(256, 72));
        jPanel2.setMinimumSize(new java.awt.Dimension(256, 72));
        jPanel2.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("S./");

        txtIngresoMensual.setEditable(false);
        txtIngresoMensual.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtIngresoMensual.setForeground(new java.awt.Color(153, 0, 0));
        txtIngresoMensual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtIngresoMensual, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIngresoMensual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelIngresos.add(jPanel2);
        jPanel2.setBounds(10, 550, 250, 78);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
public static void Actualizar() {
        String[] Fecha = Cliente.lbFecha.getText().split("-");
        EIngresos.setFecha(Fecha[2] + "-" + Fecha[1]);
        txtIngresoMensual.setText(String.valueOf(CIngresos.Listar_Ingresos()));
        panelGrafico.removeAll();
        panelGrafico.add(CGraficarIngresos.graficar());
        panelGrafico.repaint();
    }
    private void calendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarioMouseClicked
        String dia = String.valueOf(calendario.getCalendar().get(Calendar.DAY_OF_MONTH));
        if (Integer.parseInt(dia) > 9) {
            dia = dia;
        } else {
            dia = "0" + dia;
        }
        String mes = String.valueOf((calendario.getCalendar().get(Calendar.MONTH) + 1));
        if (Integer.parseInt(mes) > 9) {
            mes = mes;
        } else {
            mes = "0" + mes;
        }
        String año = String.valueOf(calendario.getCalendar().get(Calendar.YEAR));
        if (btnMensualmente.getText().equals("Vista Mensual")) {

            EIngresos.setFecha(año + "-" + mes);
            txtIngresoMensual.setText(String.valueOf(CIngresos.Listar_Ingresos()));
            CGraficarIngresos g = new CGraficarIngresos();
            panelGrafico.removeAll();
            panelGrafico.add(g.graficar());
            panelGrafico.repaint();
        } else {
            
            EIngresos.setFecha(año + "-" + mes + "-" + dia);
            txtIngresoMensual.setText(String.valueOf(CIngresos.Listar_Ingresos()));
            CGraficarIngresos g = new CGraficarIngresos();
            panelGrafico.removeAll();
            panelGrafico.add(g.graficar());
            panelGrafico.repaint();
        }

    }//GEN-LAST:event_calendarioMouseClicked

    private void btnMensualmenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMensualmenteMouseClicked
        if (btnMensualmente.getText().equals("Vista Mensual")) {
            btnMensualmente.setText("Vista Diaria");
        } else {
            btnMensualmente.setText("Vista Mensual");
        }
    }//GEN-LAST:event_btnMensualmenteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMensualmente;
    public static com.toedter.calendar.JCalendar calendario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JPanel panelFecha;
    public static javax.swing.JPanel panelGrafico;
    public static javax.swing.JPanel panelIngresos;
    public static javax.swing.JTable tbIngresos;
    public static javax.swing.JTabbedPane tpListaIngresos;
    public static javax.swing.JTextField txtIngresoMensual;
    // End of variables declaration//GEN-END:variables
}
