/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaDiseño;

import static CapaDiseño.EgresosvsIngresos.panelGrafico;
import CapaNegocio.CCuota;
import CapaNegocio.CGraficarIngresosVsEgresos;
import CapaNegocio.Errores;
import Encapsulamiento.ECuota;
import Encapsulamiento.EEgresosVsIngresos;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author vladimir
 */
public class NuevaCuota extends javax.swing.JDialog {

    /**
     * Creates new form NuevaCuota
     */
    public NuevaCuota() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagen/Logo.png"));
        setIconImage(icon);
//        ImageIcon imgIcon = new ImageIcon(getClass().getResource("/Imagen/wallpaper.jpg"));
//        Image imgEscalada = imgIcon.getImage().getScaledInstance(lbImagen.getWidth(),
//                lbImagen.getHeight(), Image.SCALE_SMOOTH);
//        Icon iconoEscalado = new ImageIcon(imgEscalada);
//        lbImagen.setIcon(iconoEscalado);

        this.setModal(true);
        this.setLocationRelativeTo(null);
        txtFecha.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();

                // Verificar si la tecla pulsada no es un digito
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
                    if (caracter != '-') {
                        e.consume();  // ignorar el evento de teclado
                    }

                }
            }
        });
        txtNroCuota.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();

                // Verificar si la tecla pulsada no es un digito
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {

                    e.consume();  // ignorar el evento de teclado

                }
            }
        });
        txtImporte.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();

                // Verificar si la tecla pulsada no es un digito
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
                    if (caracter != '.') {
                        e.consume();  // ignorar el evento de teclado
                    }

                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtNroCuota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtImporte = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva cuota");
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulario de Ingreso de Cuotas", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Fecha:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(16, 32, 35, 14);

        txtFecha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true));
        txtFecha.setDateFormatString("dd-MM-yyyy");
        jPanel1.add(txtFecha);
        txtFecha.setBounds(69, 26, 90, 22);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("N° cuota:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(16, 67, 47, 14);

        txtNroCuota.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtNroCuota.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true));
        jPanel1.add(txtNroCuota);
        txtNroCuota.setBounds(81, 64, 30, 16);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Importe S./:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(16, 105, 70, 14);

        txtImporte.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtImporte.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true));
        jPanel1.add(txtImporte);
        txtImporte.setBounds(100, 100, 40, 16);

        btnGuardar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(100, 140, 80, 23);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setText("(dia-mes-año)");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(174, 32, 77, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        int seleccion1 = JOptionPane.showOptionDialog(null, "¿seguro decea añadir una nueva cuota?"/*componente padre*/, //Mensaje
                "Seleccione una opción", // Título
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, // null para icono por defecto.
                new Object[]{"Si", "No"}, // null para YES, NO y CANCEL
                "Si");
        if (seleccion1 != -1) {
            if ((seleccion1 + 1) == 1) {
                if (txtFecha.getCalendar() == null || txtNroCuota.getText().equals("") || txtImporte.getText().equals("")) {
                    Errores.Error("Todo los campos son obligatorios");
                } else {

                    ECuota.setFecha(Errores.FormatoFecha(String.valueOf(txtFecha.getCalendar().get(Calendar.DAY_OF_MONTH) + "-"
                            + (txtFecha.getCalendar().get(Calendar.MONTH) + 1) + "-"
                            + txtFecha.getCalendar().get(Calendar.YEAR))));
                    ECuota.setNroCuota(Integer.parseInt(txtNroCuota.getText()));
                    ECuota.setImporte(Double.parseDouble(txtImporte.getText()));
                    ECuota.setHora(Cliente.lbHora.getText());
                    ECuota.setIdCliente(Tratamientos.txtIdCliente.getText());
                    ECuota.setIdCrearHistorial(Integer.parseInt(Tratamientos.txtIdCrearH.getText()));
                    if (CCuota.Guardar()) {
                        Errores.Exito("Cuota Guardada exitosamente");
                        Ingreso.Actualizar();
                        EgresosvsIngresos.EgresosVsIngresosActualizar();
                        // calculo de ingreso menos egreso
                        String[] Fecha = Cliente.lbFecha.getText().split("-");
                        EEgresosVsIngresos.setFechaIngresos(Fecha[2] + "-" + Fecha[1]);
                        EEgresosVsIngresos.setFechaEgresos(Fecha[2] + "-" + Fecha[1]);
                        CGraficarIngresosVsEgresos g = new CGraficarIngresosVsEgresos();
                        panelGrafico.removeAll();
                        panelGrafico.add(g.graficar());
                        panelGrafico.repaint();

                        dispose();
                        CCuota.Listar();
                    } else {
                        Errores.Error("Error en guardar la cuota");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaCuota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaCuota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtImporte;
    private javax.swing.JTextField txtNroCuota;
    // End of variables declaration//GEN-END:variables
}
