/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaDiseño;

import CapaNegocio.CCita;
import CapaNegocio.CCliente;
import CapaNegocio.Errores;
import Encapsulamiento.ECita;
import Encapsulamiento.ECliente;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author vladimir
 */
public class NuevaCita extends javax.swing.JDialog {

    boolean v = true;
    boolean f = false;

    /**
     * Creates new form NuevaCita
     */
    public NuevaCita() {
        initComponents();

        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagen/Logo.png"));
        setIconImage(icon);

//        ImageIcon imgIcon = new ImageIcon(getClass().getResource("/Imagen/wallpaper.jpg"));
//        Image imgEscalada = imgIcon.getImage().getScaledInstance(lbImagen.getWidth(),
//                lbImagen.getHeight(), Image.SCALE_SMOOTH);
//        Icon iconoEscalado = new ImageIcon(imgEscalada);
//        lbImagen.setIcon(iconoEscalado);

        this.setModal(true);
        this.setLocationRelativeTo(null);
        VistaInicio();
        txtDNI.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();

                // Verificar si la tecla pulsada no es un digito
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
                    e.consume();  // ignorar el evento de teclado
                }
            }
        });
        txtT.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();

                // Verificar si la tecla pulsada no es un digito
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
                    e.consume();  // ignorar el evento de teclado
                }
            }
        });
        txtHoraReserva.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();

                // Verificar si la tecla pulsada no es un digito
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
                    if (caracter != ':') {
                        e.consume();  // ignorar el evento de teclado
                    }

                }
            }
        });
        txtFecha.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char caracter = e.getKeyChar();

                // Verificar si la tecla pulsada no es un digito
                if (((caracter < '0')
                        || (caracter > '9'))
                        && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
                    if (caracter != '-') {
                        e.consume();  // ignorar el evento de teclado
                    }

                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelOpcionesCita = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAP = new javax.swing.JTextField();
        txtAM = new javax.swing.JTextField();
        txtN = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        txtT = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rbNC = new javax.swing.JRadioButton();
        rbCR = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtHoraReserva = new javax.swing.JTextField();
        cbHorario = new javax.swing.JComboBox();
        txtFecha = new com.toedter.calendar.JDateChooser();
        lbConsultar = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMotivoConsulta = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva cita");
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(299, 690));
        jPanel1.setMinimumSize(new java.awt.Dimension(299, 690));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        panelOpcionesCita.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones de Reserva", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(0, 102, 102))); // NOI18N
        panelOpcionesCita.setOpaque(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Cliente", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 8), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Apellido Paterno:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Apellido Materno:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("DNI:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel6.setText("Telefono:");

        txtAP.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtAP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true));

        txtAM.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtAM.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true));

        txtN.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true));

        txtDNI.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtDNI.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true));

        txtT.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAP, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAM, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtT, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente Registrado", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 8), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel3.setOpaque(false);

        btnBuscar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setText("Nombre cliente:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar))
        );

        rbNC.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rbNC.setText("Nuevo Cliente");
        rbNC.setOpaque(false);
        rbNC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbNCMouseClicked(evt);
            }
        });

        rbCR.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        rbCR.setText("Cliente Registrado");
        rbCR.setOpaque(false);
        rbCR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbMouseClicked1(evt);
            }
        });

        javax.swing.GroupLayout panelOpcionesCitaLayout = new javax.swing.GroupLayout(panelOpcionesCita);
        panelOpcionesCita.setLayout(panelOpcionesCitaLayout);
        panelOpcionesCitaLayout.setHorizontalGroup(
            panelOpcionesCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcionesCitaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbNC)
                .addGap(175, 175, 175))
            .addGroup(panelOpcionesCitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpcionesCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rbCR)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOpcionesCitaLayout.setVerticalGroup(
            panelOpcionesCitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesCitaLayout.createSequentialGroup()
                .addComponent(rbNC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(panelOpcionesCita);
        panelOpcionesCita.setBounds(13, 0, 280, 322);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha y Hora", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel4.setOpaque(false);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("Hora de Reserva:");

        txtHoraReserva.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        txtHoraReserva.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 51), 1, true));

        cbHorario.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        cbHorario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AM", "PM" }));

        txtFecha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 102), 1, true));
        txtFecha.setDateFormatString("dd-MM-yyyy");
        txtFecha.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N

        lbConsultar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        lbConsultar.setForeground(new java.awt.Color(102, 0, 0));
        lbConsultar.setText("Consultar");
        lbConsultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbConsultarMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jLabel9.setText("(dia-mes-año)");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setText("Fecha de Reserva:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtHoraReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 56, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbConsultar)
                .addGap(61, 61, 61))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtHoraReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(8, 348, 290, 120);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Motivo de Consulta", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 10), new java.awt.Color(153, 0, 0))); // NOI18N
        jPanel5.setOpaque(false);

        txtMotivoConsulta.setColumns(20);
        txtMotivoConsulta.setRows(5);
        txtMotivoConsulta.setOpaque(false);
        jScrollPane1.setViewportView(txtMotivoConsulta);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 481, 300, 160);

        btnGuardar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(10, 659, 80, 23);

        btnModificar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        jPanel1.add(btnModificar);
        btnModificar.setBounds(109, 659, 83, 23);

        btnEliminar.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        jPanel1.add(btnEliminar);
        btnEliminar.setBounds(210, 660, 77, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void VistaInicio() {

        rbNC.setSelected(v);
        txtAP.setEnabled(v);
        txtAM.setEnabled(v);
        txtN.setEnabled(v);
        txtDNI.setEnabled(v);
        txtT.setEnabled(v);
        rbCR.setSelected(f);
        txtNombre.setEnabled(f);
        btnBuscar.setEnabled(f);
    }
    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        ClientesBuscados cb = new ClientesBuscados();
        ECliente.setNombre(NuevaCita.txtNombre.getText());
        CCita.Listar();
        cb.setVisible(true);
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        int seleccion1 = JOptionPane.showOptionDialog(null, "¿seguro decea Guardar?"/*componente padre*/, //Mensaje
                "Seleccione una opción", // Título
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, // null para icono por defecto.
                new Object[]{"Si", "No"}, // null para YES, NO y CANCEL
                "Si");
        if (seleccion1 != -1) {
            if ((seleccion1 + 1) == 1) {
                if (rbNC.isSelected()) {
                    if (txtAP.getText().equals("") || txtAM.getText().equals("") || txtN.getText().equals("") || txtDNI.getText().equals("") || txtHoraReserva.getText().equals("") || txtFecha.getCalendar() == null || txtMotivoConsulta.getText().equals("")) {
                        Errores.Error("Los campos en rojo son obligatorios");
                    } else {
                        ECliente.setApellidoPaterno(txtAP.getText());
                        ECliente.setApellidoMaterno(txtAM.getText());
                        ECliente.setNombre(txtN.getText());
                        ECliente.setDNI(txtDNI.getText());
                        if (txtT.getText().equals("")) {
                            ECliente.setTelefono("0");
                        } else {
                            ECliente.setTelefono(txtT.getText());
                        }
                        ECita.setHora(txtHoraReserva.getText() + " " + cbHorario.getSelectedItem().toString());
                        ECita.setFecha(Errores.FormatoFecha(String.valueOf(txtFecha.getCalendar().get(Calendar.DAY_OF_MONTH) + "-"
                                + (txtFecha.getCalendar().get(Calendar.MONTH) + 1) + "-"
                                + txtFecha.getCalendar().get(Calendar.YEAR))));
                        ECita.setMotivo(txtMotivoConsulta.getText());
                        ECliente.setEdad("0");
                        ECliente.setFechaNacimiento("0001-01-01");
                        ECliente.setDireccion("");
                        ECliente.setParentesco("");
                        if (CCita.Guardar1()) {

                            String[] Fecha = Cliente.lbFecha.getText().split("-");
                            ECita.setFecha(Fecha[2] + "-" + Fecha[1]);
                            CCita.Listar_Por_Fecha();
                            CCliente.Listar();
                            Errores.Exito("Datos guardado correctamente");
                            dispose();
                        } else {
                            Errores.Error("Ocurrio un error al intentar guardar ");
                        }
                    }
                } else {
                    if (txtHoraReserva.getText().equals("") || txtFecha.getCalendar() == null || txtMotivoConsulta.getText().equals("")) {
                        Errores.Error("Los campos de hora, fecha, motivo son obligatorios");
                    } else {
                        ECita.setHora(txtHoraReserva.getText() + " " + cbHorario.getSelectedItem().toString());
                        ECita.setFecha(Errores.FormatoFecha(String.valueOf(txtFecha.getCalendar().get(Calendar.DAY_OF_MONTH) + "-"
                                + (txtFecha.getCalendar().get(Calendar.MONTH) + 1) + "-"
                                + txtFecha.getCalendar().get(Calendar.YEAR))));
                        ECita.setMotivo(txtMotivoConsulta.getText());
                        if (CCita.Guardar()) {
                            String[] Fecha = Cliente.lbFecha.getText().split("-");
                            ECita.setFecha(Fecha[2] + "-" + Fecha[1]);
                            CCita.Listar_Por_Fecha();
                            CCliente.Listar();
                            Errores.Exito("Cita guardada correctamente");
                            dispose();
                        } else {
                            Errores.Error("Ocurrio un error al intentar guardar ");
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    private void rbMouseClicked1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbMouseClicked1

        rbNC.setSelected(f);
        txtAP.setEnabled(f);
        txtAM.setEnabled(f);
        txtN.setEnabled(f);
        txtDNI.setEnabled(f);
        txtT.setEnabled(f);
        rbCR.setSelected(v);
        txtNombre.setEnabled(v);
        btnBuscar.setEnabled(v);

    }//GEN-LAST:event_rbMouseClicked1

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        int seleccion1 = JOptionPane.showOptionDialog(null, "¿seguro decea modificar?"/*componente padre*/, //Mensaje
                "Seleccione una opción", // Título
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, // null para icono por defecto.
                new Object[]{"Si", "No"}, // null para YES, NO y CANCEL
                "Si");
        if (seleccion1 != -1) {
            if ((seleccion1 + 1) == 1) {
                if (txtHoraReserva.getText().equals("") || txtFecha.getCalendar() == null || txtMotivoConsulta.getText().equals("")) {
                    Errores.Error("Los campos de Hora, Fecha y Motivo son obligatorios");
                } else {
                    ECita.setHora(txtHoraReserva.getText() + " " + cbHorario.getSelectedItem().toString());
                    ECita.setFecha(Errores.FormatoFecha(String.valueOf(txtFecha.getCalendar().get(Calendar.DAY_OF_MONTH) + "-"
                            + (txtFecha.getCalendar().get(Calendar.MONTH) + 1) + "-"
                            + txtFecha.getCalendar().get(Calendar.YEAR))));
                    ECita.setMotivo(txtMotivoConsulta.getText());
                    if (CCita.Modificar()) {
                        String[] Fecha = Cliente.lbFecha.getText().split("-");
                        ECita.setFecha(Fecha[2] + "-" + Fecha[1]);
                        CCita.Listar_Por_Fecha();
                        Errores.Exito("Se actualizo correctamente");
                        dispose();
                    } else {
                        Errores.Error("Ocurrio un error al intentar actualizar");
                    }
                }
            }
        }

    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        int seleccion1 = JOptionPane.showOptionDialog(null, "¿seguro decea eliminar?"/*componente padre*/, //Mensaje
                "Seleccione una opción", // Título
                JOptionPane.YES_NO_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, // null para icono por defecto.
                new Object[]{"Si", "No"}, // null para YES, NO y CANCEL
                "Si");
        if (seleccion1 != -1) {
            if ((seleccion1 + 1) == 1) {
                if (CCita.Eliminar()) {
                    String[] Fecha = Cliente.lbFecha.getText().split("-");
                    ECita.setFecha(Fecha[2] + "-" + Fecha[1]);
                    CCita.Listar_Por_Fecha();
                    Errores.Exito("Cita correctamente eliminada");
                    dispose();
                } else {
                    Errores.Error("Ocurrio un error al intentar eliminar la cita");
                }
            }
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void lbConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbConsultarMouseClicked
        if (txtFecha.getCalendar() != null) {
            String dia = String.valueOf(txtFecha.getCalendar().get(Calendar.DAY_OF_MONTH));
            if (Integer.parseInt(dia) > 9) {
                dia = dia;
            } else {
                dia = "0" + dia;
            }
            String mes = String.valueOf((txtFecha.getCalendar().get(Calendar.MONTH) + 1));
            if (Integer.parseInt(mes) > 9) {
                mes = mes;
            } else {
                mes = "0" + mes;
            }
            String año = String.valueOf(txtFecha.getCalendar().get(Calendar.YEAR));
            ECita.setFecha(año + "-" + mes + "-" + dia);

            ConsultarFecha cf = new ConsultarFecha();
            CCita.Consulta();
            cf.setLocationRelativeTo(null);
            cf.setVisible(true);
        }

    }//GEN-LAST:event_lbConsultarMouseClicked

    private void rbNCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbNCMouseClicked
        rbNC.setSelected(v);
        txtAP.setEnabled(v);
        txtAM.setEnabled(v);
        txtN.setEnabled(v);
        txtDNI.setEnabled(v);
        txtT.setEnabled(v);
        rbCR.setSelected(f);
        txtNombre.setEnabled(f);
        btnBuscar.setEnabled(f);
    }//GEN-LAST:event_rbNCMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaCita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaCita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnBuscar;
    public static javax.swing.JButton btnEliminar;
    public static javax.swing.JButton btnGuardar;
    public static javax.swing.JButton btnModificar;
    public static javax.swing.JComboBox cbHorario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbConsultar;
    public static javax.swing.JPanel panelOpcionesCita;
    public static javax.swing.JRadioButton rbCR;
    public static javax.swing.JRadioButton rbNC;
    public static javax.swing.JTextField txtAM;
    public static javax.swing.JTextField txtAP;
    public static javax.swing.JTextField txtDNI;
    public static com.toedter.calendar.JDateChooser txtFecha;
    public static javax.swing.JTextField txtHoraReserva;
    public static javax.swing.JTextArea txtMotivoConsulta;
    public static javax.swing.JTextField txtN;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtT;
    // End of variables declaration//GEN-END:variables
}
