/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CapaDiseño;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author vladimir
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagen/Logo.png"));
        setIconImage(icon);
        //para poner imagen y color a un JTabbedPane
//        tpanelVistaPrincipal.setIconAt(0, new ImageIcon("/Imagen/clientes.png"));
//        tpanelVistaPrincipal.setBackgroundAt(1, Color.yellow);
        this.setLocationRelativeTo(null);

//        tpanelVistaPrincipal.setIconAt(1, new ImageIcon("kopete011.gif"));
//        tpanelVistaPrincipal.setIconAt(2, new ImageIcon("kopete012.gif"));
//        tpanelVistaPrincipal.setIconAt(3, new ImageIcon("kopete013.gif"));
//        tpanelVistaPrincipal.setIconAt(4, new ImageIcon("kopete012.gif"));
//        tpanelVistaPrincipal.setIconAt(5, new ImageIcon("kopete013.gif"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpanelVistaPrincipal = new javax.swing.JTabbedPane();
        cliente1 = new CapaDiseño.Cliente();
        cita1 = new CapaDiseño.Cita();
        economia2 = new CapaDiseño.Economia();
        consulta1 = new CapaDiseño.Consulta();
        precios1 = new CapaDiseño.Precios();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 724));
        setMinimumSize(new java.awt.Dimension(1024, 724));
        setPreferredSize(new java.awt.Dimension(1024, 724));
        setResizable(false);

        tpanelVistaPrincipal.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        tpanelVistaPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpanelVistaPrincipalMouseClicked(evt);
            }
        });
        tpanelVistaPrincipal.addTab("Cliente", cliente1);
        tpanelVistaPrincipal.addTab("Cita", cita1);
        tpanelVistaPrincipal.addTab("Economia", economia2);
        tpanelVistaPrincipal.addTab("Consultas", consulta1);
        tpanelVistaPrincipal.addTab("Mis Precios", precios1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpanelVistaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpanelVistaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tpanelVistaPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpanelVistaPrincipalMouseClicked
        //
        //        if (tpanelVistaPrincipal.getSelectedIndex() == 6) {
            //            VentanaCalculadora c = new VentanaCalculadora();
            //            c.setLocationRelativeTo(null);
            //            c.setVisible(true);
            //        }
    }//GEN-LAST:event_tpanelVistaPrincipalMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private CapaDiseño.Cita cita1;
    private CapaDiseño.Cliente cliente1;
    private CapaDiseño.Consulta consulta1;
    private CapaDiseño.Economia economia2;
    private CapaDiseño.Precios precios1;
    public static javax.swing.JTabbedPane tpanelVistaPrincipal;
    // End of variables declaration//GEN-END:variables
}
